/********************************************************************
* rootDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error rootDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablerootDict();
extern void G__cpp_setup_inheritancerootDict();
extern void G__cpp_setup_typetablerootDict();
extern void G__cpp_setup_memvarrootDict();
extern void G__cpp_setup_globalrootDict();
extern void G__cpp_setup_memfuncrootDict();
extern void G__cpp_setup_funcrootDict();
extern void G__set_cpp_environmentrootDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../include/TCaloHitRoot.hh"
#include "../include/TRawCaloHitRoot.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__rootDictLN_TClass;
extern G__linked_taginfo G__rootDictLN_TBuffer;
extern G__linked_taginfo G__rootDictLN_TMemberInspector;
extern G__linked_taginfo G__rootDictLN_TObject;
extern G__linked_taginfo G__rootDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__rootDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__rootDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__rootDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__rootDictLN_TCaloHitRoot;
extern G__linked_taginfo G__rootDictLN_TRawCaloHitRoot;

/* STUB derived class for protected member access */
